# Generated by Django 4.1.3 on 2022-11-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
    ]
