# Generated by Django 4.1.3 on 2022-11-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
